# Generated by Django 5.2 on 2025-06-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='cover_image',
        ),
    ]
